SELECT ID, 
 CASE 
  WHEN TITLE = 1 THEN 'CRITICAL'
  WHEN TITLE = 2 THEN 'HIGH'
  WHEN TITLE = 3 THEN 'MEDIUM'
  ELSE 'LOW'
 END AS COLONY_NAME
FROM (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS TITLE
    FROM ECOLI_DATA
) AS RANKED
ORDER BY ID;